### PR TITLE
IMPLY-3714 use plain artifacts

### PR DESCRIPTION
**Pull request by viatcheslavmogilevsky**
Fixes https://implydata.atlassian.net/browse/IMPLY-3714

Added archive artifacts steps at each job

### CODE REVIEW

**Comment by maytasm** [comment]
Are the artifacts in the "Build Artifacts" for each test/job separately or combined?
Looking at https://ci.qa.imply.io/job/imply-druid/job/druid/job/IMPLY-3714-test/11/artifact/, seems like it is combined. In that case, how do we deal with artifacts with the same name. For example, two integration tests (i.e. realtime index integration test and kafka index integration test slow) will produce the same artifacts (same name at the same path) such as logs/broker.log. How do we deal with this? Does it overwrites? Can we append the job name to the files? Or better maybe create separate dir with each job name

**Comment by viatcheslavmogilevsky** [comment]
@maytasm there is `env.STAGE_NAME` variable in scripted pipeline - it shows current stage, so we probably can prefix artifacts to have them from all stages separately 

l'll try to implement this

**Comment by maytasm** [comment]
@viatcheslavmogilevsky 
- Can you check if we can save the jacoco code coverage report in readable formats like HTML, CSV, XML instead? 
- I see some jobs failed on step "Archive the artifacts". The log just says:
`
Archiving artifacts
script returned exit code 1
`

**Comment by viatcheslavmogilevsky** [comment]
@maytasm 

> I see some jobs failed on step "Archive the artifacts". The log just says:

> Archiving artifacts
> script returned exit code 1

> like https://ci.qa.imply.io/blue/organizations/jenkins/imply-druid%2Fdruid/detail/IMPLY-3714-test/18/pipeline/137
is this ok?

This indicates that job is failed itself, for example `(Compile=openjdk8, Run=openjdk11 other integration test` - this jobs fails https://ci.qa.imply.io/blue/organizations/jenkins/imply-druid%2Fdruid/detail/IMPLY-3714-test/18/pipeline/164 but artifacts are done: https://ci.qa.imply.io/job/imply-druid/job/druid/job/PR-171/3/artifact/stage__Compile_openjdk8__Run_openjdk11__other_integration_test/

**Comment by viatcheslavmogilevsky** [comment]
> Can you check if we can save the jacoco code coverage report in readable formats like HTML, CSV, XML instead?

pushed changes

**Comment by viatcheslavmogilevsky** [comment]
@maytasm any thoughts?

**Pull request merged**
